// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vote } from "./Vote";
import type { WsError } from "./WsError";

export type Payload = { Error: WsError } | { Connect: { user: string, } } | { Leave: { user: string, } } | { Vote: Vote };