// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Payload } from "./Payload";

export interface WSResponse { type: string, payload: Payload, users: Array<string> | null, }